version: "3.8"

services:
  app:
    env_file: .env
    image: gestion_recette_api
    container_name: app_gestion_api
    build:
      context: .
      dockerfile: dockerfile # Le nom de fichier Docker est sensible à la casse, assurez-vous qu'il est bien 'Dockerfile'
    ports:
      - "3001:3000" # Spécifiez les ports entre guillemets
    volumes:
      - .:/app # Utilisez un chemin cohérent vers l'application dans le conteneur
      - /app/node_modules # Assurez-vous que node_modules ne soit pas écrasé par les volumes
    depends_on:
      - mysql_server
    networks:
      - app-network

  mysql_server:
    image: mysql:8.0
    container_name: mysql_bd
    environment:
      MYSQL_DATABASE: bd # Utilisez la syntaxe correcte pour les variables d'environnement
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpassword # Ajout d'une variable ROOT obligatoire pour MySQL
    ports:
      - "3307:3306" # Port standard pour MySQL
    volumes:
      - mysql_data:/var/lib/mysql # Utilisation d'un volume pour la persistance des données
    networks:
      - app-network

volumes:
  mysql_data: # Déclaration d'un volume pour la base de données

networks:
  app-network: # Créez un réseau pour connecter l'application et la base de données
