version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3308:3306'

  app:
    env_file: .env
    image: gestion_restful
    container_name: gestion_restful
    build:
      context: .
    volumes:
      - .:/index
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
      DB_PORT: 3308
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db-data:
